name: Deploy to IAG Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.REMOTE_SSH_KEY }}

    - name: Pull Repository on Remote Server
      env:
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
      run: |
        ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "cd $REMOTE_PATH && git stash && git pull origin main && chmod -R 777 ../test-actions"
